
platform :ios, "13.0"
flutter_application_path = '../demo_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  
target 'SwiftDemo' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'R.swift'
  pod 'MonkeyKing'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'Dollar'

  post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
  end

end
